sudo: required
services:
  - docker

before_install: 
  - docker build -t tobiasaditya/react-test -f ./client/Dockerfile.dev ./client

script: 
  - docker run -e CI=true tobiasaditya/react-test npm run test

after_success: 
  - docker build -t tobiasaditya/multi-client ./client
  - docker build -t tobiasaditya/multi-nginx  ./nginx
  - docker build -t tobiasaditya/multi-server ./server
  - docker build -t tobiasaditya/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push tobiasaditya/multi-client
  - docker push tobiasaditya/multi-nginx
  - docker push tobiasaditya/multi-server
  - docker push tobiasaditya/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-2"
  app: "multi-docker"
  env: "Multi-docker-env"
  bucket_name: "elasticbeanstalk-ap-southeast-2-249762603254"
  bucket_path: "multi-docker"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
  
