version: '3'

services:
  postgres:
    image: 'postgres:13.2-alpine'
    environment:
      - POSTGRES_PASSWORD=postgres_password
  redis:
    image: 'redis:7.0-alpine'
  nginx:
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    restart: always
    ports:
      - '3050:80'
    depends_on:
      - api
      - client

  api:
    build: 
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
     - /home/node/app/node_modules
     - ./server:/home/node/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGPORT=5432
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
  client:
    build: 
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
     - /home/node/app/node_modules
     - ./client:/home/node/app
    environment:
      - WDS_SOCKET_PORT=0
  worker:
    build: 
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
     - /home/node/app/node_modules
     - ./worker:/home/node/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379    
    
