version: '3'
services:
  client:
    image: tobiasadiya/multi-client
    mem_limit: 128m
    hostname: client
  server:
    image: tobiasadiya/multi-server
    hostname: api
    mem_limit: 128m
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGPORT=$PGPORT
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
  worker:
    image: tobiasadiya/multi-worker
    mem_limit: 128m
    hostname: worker
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
  nginx:
    image: tobiasadiya/multi-nginx
    mem_limit: 128m
    hostname: nginx
    ports:
      - "80:80"
  